name: Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Generate a timestamp and store it in a variable
    - name: Generate Timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"

        
    - name: Build the Docker image
      run: |
        TIMESTAMP="${{ steps.timestamp.outputs.timestamp }}"
        docker build . --file Dockerfile --tag gallexy/chatollama:${TIMESTAMP}
        docker tag gallexy/chatollama:${TIMESTAMP} gallexy/chatollama:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to registry
      run: |
        TIMESTAMP="${{ steps.timestamp.outputs.timestamp }}"
        docker push gallexy/chatollama:${TIMESTAMP}
        docker push gallexy/chatollama:latest
